CREATE TABLE EMPLOYEE(
	ID INT NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	SALARY Decimal NOT NULL,
	PRIMARY KEY (ID)
	);

	SELECT * FROM EMPLOYEE

	SELECT COUNT(*) FROM EMPLOYEE

	INSERT INTO EMPLOYEE VALUES (101, 'VENKAT', 50000)
	INSERT INTO EMPLOYEE VALUES (102, 'SACHIN', 40000)
	INSERT INTO EMPLOYEE VALUES (103, 'PREM', 30000)
	INSERT INTO EMPLOYEE VALUES (104, 'AKHILESH', 60000)